---
title: "More populated cities with a woman as a mayor"
author: "Jesús López de Leyva"
date: "11/6/2019"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## More populated cities with a woman as a major

```{r warning=FALSE, message=FALSE}
library(SPARQL) # SPARQL querying package
library(ggplot2)
library(tidyverse)

endpoint <- "https://query.wikidata.org/sparql"
query <- '#Ciudades más pobladas con una mujer como alcaldesa\n#added before 2016-10\n#TEMPLATE={"template":"Largest ?c with ?sex head of government","variables":{"?sex":{"query":" SELECT ?id WHERE { ?id wdt:P31 wd:Q48264 .  } "},"?c":{"query":"SELECT DISTINCT ?id WHERE {  ?c wdt:P31 ?id.  ?c p:P6 ?mayor. }"} } }\nSELECT DISTINCT ?city ?cityLabel ?mayor ?mayorLabel\nWHERE\n{\n  BIND(wd:Q6581072 AS ?sex)\n  BIND(wd:Q515 AS ?c)\n\n	?city wdt:P31/wdt:P279* ?c .  # find instances of subclasses of city\n	?city p:P6 ?statement .            # with a P6 (head of goverment) statement\n	?statement ps:P6 ?mayor .          # ... that has the value ?mayor\n	?mayor wdt:P21 ?sex .       # ... where the ?mayor has P21 (sex or gender) female\n	FILTER NOT EXISTS { ?statement pq:P582 ?x }  # ... but the statement has no P582 (end date) qualifier\n	\n	# Now select the population value of the ?city\n	# (wdt: properties use only statements of "preferred" rank if any, usually meaning "current population")\n	?city wdt:P1082 ?population .\n	# Optionally, find English labels for city and mayor:\n	SERVICE wikibase:label {\n		bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" .\n	}\n}\nORDER BY DESC(?population)\nLIMIT 20'

qd <- SPARQL(endpoint,query)
df <- qd$results
```

```{r}
df %>% select(2, 4)
```


